// Automatically generated by scripts/generate_portfolio_data.js
// DO NOT EDIT DIRECTLY

export interface MediaItem {
  id: string;
  type: "photo" | "video";
  title: string;
  category: string;
  project: string;
  src: string;
  videoUrl?: string;
  metadata: {
    camera: string;
    lens: string;
    aperture: string;
    shutter: string;
    iso: string;
    focalLength?: string;
    location: string;
    date: string;
  };
}

export const portfolioItems: MediaItem[] = [
  {
    "id": "video-genki-prints-comiccon-recap",
    "type": "video",
    "title": "Comiccon Recap",
    "category": "Event / Documentary",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Event/comiccon_recap.mp4",
    "videoUrl": "/portfolio/Genki Prints/Event/comiccon_recap.mp4",
    "metadata": {
      "camera": "Sony FX6 Cinema",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/2.8",
      "shutter": "1/120s",
      "iso": "800",
      "location": "COMIC-CON, SAN DIEGO",
      "date": "JULY 2025"
    }
  },
  {
    "id": "video-glyf-studio-glyfstudio-documentary",
    "type": "video",
    "title": "Glyfstudio Documentary",
    "category": "Campaign / Brand Film",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Video/glyfstudio_documentary.mp4",
    "videoUrl": "/portfolio/GLYF STUDIO/Video/glyfstudio_documentary.mp4",
    "metadata": {
      "camera": "RED V-Raptor 8K",
      "lens": "Cooke Anamorphic /i 2x",
      "aperture": "T2.3",
      "shutter": "180 deg",
      "iso": "800",
      "location": "GLYF HARAJUKU STAGE",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "video-quinceanera-kitestudios6-1552332668-1997433444191352927-3895010458",
    "type": "video",
    "title": "1552332668 1997433444191352927 3895010458",
    "category": "Event / Cinematic",
    "project": "Quinceanera",
    "src": "/portfolio/Quinceanera/kitestudios6_1552332668_1997433444191352927_3895010458.mp4",
    "videoUrl": "/portfolio/Quinceanera/kitestudios6_1552332668_1997433444191352927_3895010458.mp4",
    "metadata": {
      "camera": "Sony FX3 Cinema",
      "lens": "FE 50mm f/1.2 GM",
      "aperture": "f/1.2",
      "shutter": "1/240s",
      "iso": "320",
      "location": "THE PLAZA HOTEL, LA",
      "date": "APRIL 2025"
    }
  },
  {
    "id": "video-tdm-redroom",
    "type": "video",
    "title": "Redroom",
    "category": "Commercial / Fashion",
    "project": "TDM",
    "src": "/portfolio/TDM/Redroom.mp4",
    "videoUrl": "/portfolio/TDM/Redroom.mp4",
    "metadata": {
      "camera": "ARRI Alexa Mini LF",
      "lens": "Angenieux Optimo Ultra 12x",
      "aperture": "T2.0",
      "shutter": "172.8 deg",
      "iso": "800",
      "location": "REDROOM STAGE, LA",
      "date": "MAY 2025"
    }
  },
  {
    "id": "video-tdm-saveclip-app-aqotn44ffv-gibzoxplw4j0jwpkvarqrkvnleat95w4wfhui0tq5vi4-uhneegq-azk7u14ele0zxqfe2-2awrnywyjxbe-npgaiw-o",
    "type": "video",
    "title": "Aqotn44ffv Gibzoxplw4j0jwpkvarqrkvnleat95w4wfhui0tq5vi4 Uhneegq Azk7u14ele0zxqfe2 2awrnywyjxbe Npgaiw O",
    "category": "Commercial / Fashion",
    "project": "TDM",
    "src": "/portfolio/TDM/SaveClip.App_AQOTN44FFv_GibzOXplW4J0JWpKvaRqRKVnLeAt95w4wfhUi0Tq5VI4-UHnEeGq-aZk7u14ELe0ZxqfE2_2awRNYWYJXBE-npGaiW_o.mp4",
    "videoUrl": "/portfolio/TDM/SaveClip.App_AQOTN44FFv_GibzOXplW4J0JWpKvaRqRKVnLeAt95w4wfhUi0Tq5VI4-UHnEeGq-aZk7u14ELe0ZxqfE2_2awRNYWYJXBE-npGaiW_o.mp4",
    "metadata": {
      "camera": "ARRI Alexa Mini LF",
      "lens": "Angenieux Optimo Ultra 12x",
      "aperture": "T2.0",
      "shutter": "172.8 deg",
      "iso": "800",
      "location": "REDROOM STAGE, LA",
      "date": "MAY 2025"
    }
  },
  {
    "id": "video-toandme-test",
    "type": "video",
    "title": "Test",
    "category": "Editorial / Brand",
    "project": "TOANDME",
    "src": "/portfolio/TOANDME/TEST.mp4",
    "videoUrl": "/portfolio/TOANDME/TEST.mp4",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Summicron-SL 50mm f/2 ASPH",
      "aperture": "f/2.0",
      "shutter": "1/200s",
      "iso": "200",
      "location": "MALIBU COAST, CALIFORNIA",
      "date": "JUNE 2025"
    }
  },
  {
    "id": "video-toandme-to-and-me-advertisement-2",
    "type": "video",
    "title": "To And Me Advertisement 2",
    "category": "Editorial / Brand",
    "project": "TOANDME",
    "src": "/portfolio/TOANDME/To_and_Me_Advertisement_2.mp4",
    "videoUrl": "/portfolio/TOANDME/To_and_Me_Advertisement_2.mp4",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Summicron-SL 50mm f/2 ASPH",
      "aperture": "f/2.0",
      "shutter": "1/200s",
      "iso": "200",
      "location": "MALIBU COAST, CALIFORNIA",
      "date": "JUNE 2025"
    }
  },
  {
    "id": "photo-ecommerce-0d1f7b25-872c-4763-8ed0-c6d7ecd427f3-rw-1920",
    "type": "photo",
    "title": "ECOMMERCE SHOT",
    "category": "Product / E-commerce",
    "project": "Ecommerce",
    "src": "/portfolio/Ecommerce/0d1f7b25-872c-4763-8ed0-c6d7ecd427f3_rw_1920.jpg",
    "metadata": {
      "camera": "Phase One XF 150MP",
      "lens": "Schneider Kreuznach 80mm f/2.8",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "50",
      "location": "KITE STUDIOS - STUDIO C",
      "date": "MARCH 2026"
    }
  },
  {
    "id": "photo-ecommerce-34f9863e-c1a4-4866-9493-9f47ea5d063d-rw-1920",
    "type": "photo",
    "title": "ECOMMERCE SHOT",
    "category": "Product / E-commerce",
    "project": "Ecommerce",
    "src": "/portfolio/Ecommerce/34f9863e-c1a4-4866-9493-9f47ea5d063d_rw_1920.jpg",
    "metadata": {
      "camera": "Phase One XF 150MP",
      "lens": "Schneider Kreuznach 80mm f/2.8",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "50",
      "location": "KITE STUDIOS - STUDIO C",
      "date": "MARCH 2026"
    }
  },
  {
    "id": "photo-ecommerce-4737399a-2610-4883-b262-062813e7abea-rw-1920",
    "type": "photo",
    "title": "ECOMMERCE SHOT",
    "category": "Product / E-commerce",
    "project": "Ecommerce",
    "src": "/portfolio/Ecommerce/4737399a-2610-4883-b262-062813e7abea_rw_1920.jpg",
    "metadata": {
      "camera": "Phase One XF 150MP",
      "lens": "Schneider Kreuznach 80mm f/2.8",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "50",
      "location": "KITE STUDIOS - STUDIO C",
      "date": "MARCH 2026"
    }
  },
  {
    "id": "photo-ecommerce-66dddbb2-03aa-41bf-b5a2-77a4a8c9143e-rw-1920",
    "type": "photo",
    "title": "ECOMMERCE SHOT",
    "category": "Product / E-commerce",
    "project": "Ecommerce",
    "src": "/portfolio/Ecommerce/66dddbb2-03aa-41bf-b5a2-77a4a8c9143e_rw_1920.jpg",
    "metadata": {
      "camera": "Phase One XF 150MP",
      "lens": "Schneider Kreuznach 80mm f/2.8",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "50",
      "location": "KITE STUDIOS - STUDIO C",
      "date": "MARCH 2026"
    }
  },
  {
    "id": "photo-ecommerce-68fe812d-1f5b-4759-a7c5-cfa69c9c1f36-rw-1920",
    "type": "photo",
    "title": "ECOMMERCE SHOT",
    "category": "Product / E-commerce",
    "project": "Ecommerce",
    "src": "/portfolio/Ecommerce/68fe812d-1f5b-4759-a7c5-cfa69c9c1f36_rw_1920.jpg",
    "metadata": {
      "camera": "Phase One XF 150MP",
      "lens": "Schneider Kreuznach 80mm f/2.8",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "50",
      "location": "KITE STUDIOS - STUDIO C",
      "date": "MARCH 2026"
    }
  },
  {
    "id": "photo-ecommerce-a694331a-863e-4090-8de4-4c7de75cfbcd-rw-1920",
    "type": "photo",
    "title": "ECOMMERCE SHOT",
    "category": "Product / E-commerce",
    "project": "Ecommerce",
    "src": "/portfolio/Ecommerce/a694331a-863e-4090-8de4-4c7de75cfbcd_rw_1920.jpg",
    "metadata": {
      "camera": "Phase One XF 150MP",
      "lens": "Schneider Kreuznach 80mm f/2.8",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "50",
      "location": "KITE STUDIOS - STUDIO C",
      "date": "MARCH 2026"
    }
  },
  {
    "id": "photo-ecommerce-b22eccad-2ed6-4535-a29d-b7087aea8cac-rw-1920",
    "type": "photo",
    "title": "ECOMMERCE SHOT",
    "category": "Product / E-commerce",
    "project": "Ecommerce",
    "src": "/portfolio/Ecommerce/b22eccad-2ed6-4535-a29d-b7087aea8cac_rw_1920.jpg",
    "metadata": {
      "camera": "Phase One XF 150MP",
      "lens": "Schneider Kreuznach 80mm f/2.8",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "50",
      "location": "KITE STUDIOS - STUDIO C",
      "date": "MARCH 2026"
    }
  },
  {
    "id": "photo-ecommerce-cad446f4-93ab-42b6-a6b7-65c9c8713714-rw-1920",
    "type": "photo",
    "title": "ECOMMERCE SHOT",
    "category": "Product / E-commerce",
    "project": "Ecommerce",
    "src": "/portfolio/Ecommerce/cad446f4-93ab-42b6-a6b7-65c9c8713714_rw_1920.jpg",
    "metadata": {
      "camera": "Phase One XF 150MP",
      "lens": "Schneider Kreuznach 80mm f/2.8",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "50",
      "location": "KITE STUDIOS - STUDIO C",
      "date": "MARCH 2026"
    }
  },
  {
    "id": "photo-ecommerce-d27a69c2-5e89-4325-aa2a-fce9fcdddeb1-rw-1920",
    "type": "photo",
    "title": "ECOMMERCE SHOT",
    "category": "Product / E-commerce",
    "project": "Ecommerce",
    "src": "/portfolio/Ecommerce/d27a69c2-5e89-4325-aa2a-fce9fcdddeb1_rw_1920.jpg",
    "metadata": {
      "camera": "Phase One XF 150MP",
      "lens": "Schneider Kreuznach 80mm f/2.8",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "50",
      "location": "KITE STUDIOS - STUDIO C",
      "date": "MARCH 2026"
    }
  },
  {
    "id": "photo-fashion-fashion-1",
    "type": "photo",
    "title": "Fashion 1",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_1.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-10",
    "type": "photo",
    "title": "Fashion 10",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_10.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-11",
    "type": "photo",
    "title": "Fashion 11",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_11.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-12",
    "type": "photo",
    "title": "Fashion 12",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_12.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-13",
    "type": "photo",
    "title": "Fashion 13",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_13.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-14",
    "type": "photo",
    "title": "Fashion 14",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_14.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-15",
    "type": "photo",
    "title": "Fashion 15",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_15.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-16",
    "type": "photo",
    "title": "Fashion 16",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_16.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-17",
    "type": "photo",
    "title": "Fashion 17",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_17.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-18",
    "type": "photo",
    "title": "Fashion 18",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_18.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-19",
    "type": "photo",
    "title": "Fashion 19",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_19.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-2",
    "type": "photo",
    "title": "Fashion 2",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_2.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-20",
    "type": "photo",
    "title": "Fashion 20",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_20.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-21",
    "type": "photo",
    "title": "Fashion 21",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_21.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-22",
    "type": "photo",
    "title": "Fashion 22",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_22.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-23",
    "type": "photo",
    "title": "Fashion 23",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_23.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-24",
    "type": "photo",
    "title": "Fashion 24",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_24.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-25",
    "type": "photo",
    "title": "Fashion 25",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_25.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-26",
    "type": "photo",
    "title": "Fashion 26",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_26.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-27",
    "type": "photo",
    "title": "Fashion 27",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_27.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-28",
    "type": "photo",
    "title": "Fashion 28",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_28.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-29",
    "type": "photo",
    "title": "Fashion 29",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_29.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-3",
    "type": "photo",
    "title": "Fashion 3",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_3.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-30",
    "type": "photo",
    "title": "Fashion 30",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_30.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-31",
    "type": "photo",
    "title": "Fashion 31",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_31.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-32",
    "type": "photo",
    "title": "Fashion 32",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_32.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-33",
    "type": "photo",
    "title": "Fashion 33",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_33.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-34",
    "type": "photo",
    "title": "Fashion 34",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_34.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-35",
    "type": "photo",
    "title": "Fashion 35",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_35.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-36",
    "type": "photo",
    "title": "Fashion 36",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_36.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-37",
    "type": "photo",
    "title": "Fashion 37",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_37.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-38",
    "type": "photo",
    "title": "Fashion 38",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_38.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-39",
    "type": "photo",
    "title": "Fashion 39",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_39.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-4",
    "type": "photo",
    "title": "Fashion 4",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_4.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-40",
    "type": "photo",
    "title": "Fashion 40",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_40.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-5",
    "type": "photo",
    "title": "Fashion 5",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_5.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-6",
    "type": "photo",
    "title": "Fashion 6",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_6.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-7",
    "type": "photo",
    "title": "Fashion 7",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_7.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-8",
    "type": "photo",
    "title": "Fashion 8",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_8.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-fashion-fashion-9",
    "type": "photo",
    "title": "Fashion 9",
    "category": "Fashion / Editorial",
    "project": "Fashion",
    "src": "/portfolio/Fashion/fashion_9.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 50mm f/1.4",
      "aperture": "f/1.8",
      "shutter": "1/250s",
      "iso": "64",
      "location": "PARIS STUDIO B",
      "date": "DECEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-8-bit-charizard-keychain",
    "type": "photo",
    "title": "8 Bit Charizard Keychain",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/8-Bit Charizard Keychain.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-8-bit-espeon-keychain",
    "type": "photo",
    "title": "8 Bit Espeon Keychain",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/8-Bit Espeon Keychain.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-8-bit-gyarados-keychain",
    "type": "photo",
    "title": "8 Bit Gyarados Keychain",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/8-Bit Gyarados Keychain.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-8-bit-lapras-keychain",
    "type": "photo",
    "title": "8 Bit Lapras Keychain",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/8-Bit Lapras Keychain.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-8-bit-lugia-keychain",
    "type": "photo",
    "title": "8 Bit Lugia Keychain",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/8-Bit Lugia Keychain.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-gpartboard-8",
    "type": "photo",
    "title": "Gpartboard 8",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/GPArtboard 8.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-ig-pokeball-2",
    "type": "photo",
    "title": "Ig Pokeball 2",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/IG_PokeBall_2.png",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-ig-pokeball-3",
    "type": "photo",
    "title": "Ig Pokeball 3",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/IG_PokeBall_3.png",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-ig-pokeball-4",
    "type": "photo",
    "title": "Ig Pokeball 4",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/IG_PokeBall_4.png",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-ig-pokeball-5",
    "type": "photo",
    "title": "Ig Pokeball 5",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/IG_PokeBall_5.png",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-kirby-535767",
    "type": "photo",
    "title": "Kirby",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/KIRBY-535767.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-kirby-542830",
    "type": "photo",
    "title": "Kirby",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/KIRBY-542830.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-kirby-544801",
    "type": "photo",
    "title": "Kirby",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/KIRBY-544801.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-kirby-549478",
    "type": "photo",
    "title": "Kirby",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/KIRBY-549478.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-kirby-551069",
    "type": "photo",
    "title": "Kirby",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/KIRBY-551069.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-kirby-551169",
    "type": "photo",
    "title": "Kirby",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/KIRBY-551169.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-kirby-569623",
    "type": "photo",
    "title": "Kirby",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/KIRBY-569623.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-p1040872-enhanced-nr",
    "type": "photo",
    "title": "P1040872 Enhanced Nr",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/P1040872-Enhanced-NR.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-p1040876-enhanced-nr",
    "type": "photo",
    "title": "P1040876 Enhanced Nr",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/P1040876-Enhanced-NR.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-p1040880-enhanced-nr",
    "type": "photo",
    "title": "P1040880 Enhanced Nr",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/P1040880-Enhanced-NR.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-p1040913-enhanced-nr",
    "type": "photo",
    "title": "P1040913 Enhanced Nr",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/P1040913-Enhanced-NR.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-p1041291",
    "type": "photo",
    "title": "P1041291",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/P1041291.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-p1041313",
    "type": "photo",
    "title": "P1041313",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/P1041313.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-p1041321",
    "type": "photo",
    "title": "P1041321",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/P1041321.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-p1041327",
    "type": "photo",
    "title": "P1041327",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/P1041327.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-p1041329",
    "type": "photo",
    "title": "P1041329",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/P1041329.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-p1041344",
    "type": "photo",
    "title": "P1041344",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/P1041344.JPG",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-professional-product-photos-kitestudios-ecommerce-tomy-3",
    "type": "photo",
    "title": "Professional Product Photos Kitestudios Ecommerce Tomy",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/Professional-Product-Photos-KITESTUDIOS-Ecommerce-Tomy-3.png",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-valentines-day-final-1920x1080",
    "type": "photo",
    "title": "Valentines Day Final 1920x1080",
    "category": "Product / Macro",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Ecommerce/Valentines Day_Final_1920x1080.png",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 90mm f/2.8 Macro G OSS",
      "aperture": "f/5.6",
      "shutter": "1/100s",
      "iso": "100",
      "location": "KITE STUDIOS - SUITE 1",
      "date": "NOVEMBER 2025"
    }
  },
  {
    "id": "photo-genki-prints-event-1-glyf",
    "type": "photo",
    "title": "Event 1 Glyf",
    "category": "Event / Documentary",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Event/event_1_glyf.jpg",
    "metadata": {
      "camera": "Sony FX6 Cinema",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/2.8",
      "shutter": "1/120s",
      "iso": "800",
      "location": "COMIC-CON, SAN DIEGO",
      "date": "JULY 2025"
    }
  },
  {
    "id": "photo-genki-prints-event-2-team",
    "type": "photo",
    "title": "Event 2 Team",
    "category": "Event / Documentary",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Event/event_2_team.jpg",
    "metadata": {
      "camera": "Sony FX6 Cinema",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/2.8",
      "shutter": "1/120s",
      "iso": "800",
      "location": "COMIC-CON, SAN DIEGO",
      "date": "JULY 2025"
    }
  },
  {
    "id": "photo-genki-prints-event-3-gaming",
    "type": "photo",
    "title": "Event 3 Gaming",
    "category": "Event / Documentary",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Event/event_3_gaming.jpg",
    "metadata": {
      "camera": "Sony FX6 Cinema",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/2.8",
      "shutter": "1/120s",
      "iso": "800",
      "location": "COMIC-CON, SAN DIEGO",
      "date": "JULY 2025"
    }
  },
  {
    "id": "photo-genki-prints-event-4-lsprint",
    "type": "photo",
    "title": "Event 4 Lsprint",
    "category": "Event / Documentary",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Event/event_4_lsprint.jpg",
    "metadata": {
      "camera": "Sony FX6 Cinema",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/2.8",
      "shutter": "1/120s",
      "iso": "800",
      "location": "COMIC-CON, SAN DIEGO",
      "date": "JULY 2025"
    }
  },
  {
    "id": "photo-genki-prints-event-5-signed",
    "type": "photo",
    "title": "Event 5 Signed",
    "category": "Event / Documentary",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Event/event_5_signed.jpg",
    "metadata": {
      "camera": "Sony FX6 Cinema",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/2.8",
      "shutter": "1/120s",
      "iso": "800",
      "location": "COMIC-CON, SAN DIEGO",
      "date": "JULY 2025"
    }
  },
  {
    "id": "photo-genki-prints-saveclip-app-629462752-18454476853103425-3738569233577502164-n",
    "type": "photo",
    "title": "629462752 18454476853103425 3738569233577502164 N",
    "category": "Event / Documentary",
    "project": "Genki Prints",
    "src": "/portfolio/Genki Prints/Event/SaveClip.App_629462752_18454476853103425_3738569233577502164_n.jpg",
    "metadata": {
      "camera": "Sony FX6 Cinema",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/2.8",
      "shutter": "1/120s",
      "iso": "800",
      "location": "COMIC-CON, SAN DIEGO",
      "date": "JULY 2025"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-504604",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-504604.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-506411",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-506411.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-511042",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-511042.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-573583",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-573583.webp",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-591109",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-591109.webp",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-603036",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-603036.webp",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-624394",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-624394.webp",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-632750",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-632750.webp",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-661065",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-661065.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-661735",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-661735.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-661739",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-661739.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-662790",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-662790.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-996886",
    "type": "photo",
    "title": "Gallery82",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82-996886.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-hat-1041664",
    "type": "photo",
    "title": "Gallery82 Hat",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82_HAT-1041664.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-hat-1041668",
    "type": "photo",
    "title": "Gallery82 Hat",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82_HAT-1041668.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-hat-1041669",
    "type": "photo",
    "title": "Gallery82 Hat",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82_HAT-1041669.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-hat-1041670",
    "type": "photo",
    "title": "Gallery82 Hat",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82_HAT-1041670.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-purplehaze-tshirt-back-2",
    "type": "photo",
    "title": "Gallery82 Purplehaze Tshirt Back 2",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82_PURPLEHAZE_TSHIRT_BACK_2.webp",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-purplehaze-tshirt-back-3",
    "type": "photo",
    "title": "Gallery82 Purplehaze Tshirt Back 3",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82_PURPLEHAZE_TSHIRT_BACK_3.JPG",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-purplehaze-tshirt-back-76574a97-9c05-4aa8-895c-6f39d4dc35ba",
    "type": "photo",
    "title": "Gallery82 Purplehaze Tshirt Back",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82_PURPLEHAZE_TSHIRT_BACK_76574a97-9c05-4aa8-895c-6f39d4dc35ba.webp",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-gallery82-purplehaze-tshirt-front",
    "type": "photo",
    "title": "Gallery82 Purplehaze Tshirt Front",
    "category": "Product / Apparel",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Ecommerce/GALLERY82_PURPLEHAZE_TSHIRT_FRONT.png",
    "metadata": {
      "camera": "Fujifilm GFX 100S",
      "lens": "GF 120mm f/4 Macro R LM",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "100",
      "location": "GLYF HQ, TOKYO",
      "date": "JANUARY 2026"
    }
  },
  {
    "id": "photo-glyf-studio-hero-banner-clone-1",
    "type": "photo",
    "title": "Hero Banner Clone 1",
    "category": "Fashion / Lookbook",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Lookbook/Hero Banner_Clone_1.JPG",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Vario-Elmarit-SL 24-70mm f/2.8",
      "aperture": "f/2.8",
      "shutter": "1/250s",
      "iso": "200",
      "location": "SHIBUYA ARCHIVES, TOKYO",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-glyf-studio-image-16",
    "type": "photo",
    "title": "Image 16",
    "category": "Fashion / Lookbook",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Lookbook/image 16.jpg",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Vario-Elmarit-SL 24-70mm f/2.8",
      "aperture": "f/2.8",
      "shutter": "1/250s",
      "iso": "200",
      "location": "SHIBUYA ARCHIVES, TOKYO",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-glyf-studio-p1041766",
    "type": "photo",
    "title": "P1041766",
    "category": "Fashion / Lookbook",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Lookbook/P1041766.JPG",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Vario-Elmarit-SL 24-70mm f/2.8",
      "aperture": "f/2.8",
      "shutter": "1/250s",
      "iso": "200",
      "location": "SHIBUYA ARCHIVES, TOKYO",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-glyf-studio-p1041814",
    "type": "photo",
    "title": "P1041814",
    "category": "Fashion / Lookbook",
    "project": "GLYF STUDIO",
    "src": "/portfolio/GLYF STUDIO/Lookbook/P1041814.JPG",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Vario-Elmarit-SL 24-70mm f/2.8",
      "aperture": "f/2.8",
      "shutter": "1/250s",
      "iso": "200",
      "location": "SHIBUYA ARCHIVES, TOKYO",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-kevora-kevora-product-1",
    "type": "photo",
    "title": "Kevora Product 1",
    "category": "Product / Skincare",
    "project": "Kevora",
    "src": "/portfolio/Kevora/KEVORA_PRODUCT_1.png",
    "metadata": {
      "camera": "Phase One IQ4 150MP",
      "lens": "Schneider Kreuznach 120mm f/4 Macro",
      "aperture": "f/11",
      "shutter": "1/160s",
      "iso": "50",
      "location": "COPENHAGEN DESIGN LAB",
      "date": "FEBRUARY 2026"
    }
  },
  {
    "id": "photo-kevora-kevora-product-10",
    "type": "photo",
    "title": "Kevora Product 10",
    "category": "Product / Skincare",
    "project": "Kevora",
    "src": "/portfolio/Kevora/KEVORA_PRODUCT_10.jpg",
    "metadata": {
      "camera": "Phase One IQ4 150MP",
      "lens": "Schneider Kreuznach 120mm f/4 Macro",
      "aperture": "f/11",
      "shutter": "1/160s",
      "iso": "50",
      "location": "COPENHAGEN DESIGN LAB",
      "date": "FEBRUARY 2026"
    }
  },
  {
    "id": "photo-kevora-kevora-product-12",
    "type": "photo",
    "title": "Kevora Product 12",
    "category": "Product / Skincare",
    "project": "Kevora",
    "src": "/portfolio/Kevora/KEVORA_PRODUCT_12.jpg",
    "metadata": {
      "camera": "Phase One IQ4 150MP",
      "lens": "Schneider Kreuznach 120mm f/4 Macro",
      "aperture": "f/11",
      "shutter": "1/160s",
      "iso": "50",
      "location": "COPENHAGEN DESIGN LAB",
      "date": "FEBRUARY 2026"
    }
  },
  {
    "id": "photo-kevora-kevora-product-13",
    "type": "photo",
    "title": "Kevora Product 13",
    "category": "Product / Skincare",
    "project": "Kevora",
    "src": "/portfolio/Kevora/KEVORA_PRODUCT_13.jpg",
    "metadata": {
      "camera": "Phase One IQ4 150MP",
      "lens": "Schneider Kreuznach 120mm f/4 Macro",
      "aperture": "f/11",
      "shutter": "1/160s",
      "iso": "50",
      "location": "COPENHAGEN DESIGN LAB",
      "date": "FEBRUARY 2026"
    }
  },
  {
    "id": "photo-kevora-kevora-product-15",
    "type": "photo",
    "title": "Kevora Product 15",
    "category": "Product / Skincare",
    "project": "Kevora",
    "src": "/portfolio/Kevora/KEVORA_PRODUCT_15.jpg",
    "metadata": {
      "camera": "Phase One IQ4 150MP",
      "lens": "Schneider Kreuznach 120mm f/4 Macro",
      "aperture": "f/11",
      "shutter": "1/160s",
      "iso": "50",
      "location": "COPENHAGEN DESIGN LAB",
      "date": "FEBRUARY 2026"
    }
  },
  {
    "id": "photo-kevora-kevora-product-2",
    "type": "photo",
    "title": "Kevora Product 2",
    "category": "Product / Skincare",
    "project": "Kevora",
    "src": "/portfolio/Kevora/KEVORA_PRODUCT_2.jpg",
    "metadata": {
      "camera": "Phase One IQ4 150MP",
      "lens": "Schneider Kreuznach 120mm f/4 Macro",
      "aperture": "f/11",
      "shutter": "1/160s",
      "iso": "50",
      "location": "COPENHAGEN DESIGN LAB",
      "date": "FEBRUARY 2026"
    }
  },
  {
    "id": "photo-kevora-kevora-product-3",
    "type": "photo",
    "title": "Kevora Product 3",
    "category": "Product / Skincare",
    "project": "Kevora",
    "src": "/portfolio/Kevora/KEVORA_PRODUCT_3.webp",
    "metadata": {
      "camera": "Phase One IQ4 150MP",
      "lens": "Schneider Kreuznach 120mm f/4 Macro",
      "aperture": "f/11",
      "shutter": "1/160s",
      "iso": "50",
      "location": "COPENHAGEN DESIGN LAB",
      "date": "FEBRUARY 2026"
    }
  },
  {
    "id": "photo-kevora-kevora-product-7",
    "type": "photo",
    "title": "Kevora Product 7",
    "category": "Product / Skincare",
    "project": "Kevora",
    "src": "/portfolio/Kevora/KEVORA_PRODUCT_7.jpg",
    "metadata": {
      "camera": "Phase One IQ4 150MP",
      "lens": "Schneider Kreuznach 120mm f/4 Macro",
      "aperture": "f/11",
      "shutter": "1/160s",
      "iso": "50",
      "location": "COPENHAGEN DESIGN LAB",
      "date": "FEBRUARY 2026"
    }
  },
  {
    "id": "photo-kevora-kevora-product-8",
    "type": "photo",
    "title": "Kevora Product 8",
    "category": "Product / Skincare",
    "project": "Kevora",
    "src": "/portfolio/Kevora/KEVORA_PRODUCT_8.jpg",
    "metadata": {
      "camera": "Phase One IQ4 150MP",
      "lens": "Schneider Kreuznach 120mm f/4 Macro",
      "aperture": "f/11",
      "shutter": "1/160s",
      "iso": "50",
      "location": "COPENHAGEN DESIGN LAB",
      "date": "FEBRUARY 2026"
    }
  },
  {
    "id": "photo-kevora-kevora-product-9",
    "type": "photo",
    "title": "Kevora Product 9",
    "category": "Product / Skincare",
    "project": "Kevora",
    "src": "/portfolio/Kevora/KEVORA_PRODUCT_9.jpg",
    "metadata": {
      "camera": "Phase One IQ4 150MP",
      "lens": "Schneider Kreuznach 120mm f/4 Macro",
      "aperture": "f/11",
      "shutter": "1/160s",
      "iso": "50",
      "location": "COPENHAGEN DESIGN LAB",
      "date": "FEBRUARY 2026"
    }
  },
  {
    "id": "photo-platini-jeans-08cf57ba5aaf06960b7b7ea6-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Product / E-commerce",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Ecommerce Photography/08cf57ba5aaf06960b7b7ea6_rw_1920.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/5.6",
      "shutter": "1/125s",
      "iso": "100",
      "location": "DOWNTOWN LA STUDIO",
      "date": "AUGUST 2025"
    }
  },
  {
    "id": "photo-platini-jeans-4bd3dd45c58dc04fdec57950-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Product / E-commerce",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Ecommerce Photography/4bd3dd45c58dc04fdec57950_rw_1920.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/5.6",
      "shutter": "1/125s",
      "iso": "100",
      "location": "DOWNTOWN LA STUDIO",
      "date": "AUGUST 2025"
    }
  },
  {
    "id": "photo-platini-jeans-807ee5f2aaf0e95218cc19f3-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Product / E-commerce",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Ecommerce Photography/807ee5f2aaf0e95218cc19f3_rw_1920.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/5.6",
      "shutter": "1/125s",
      "iso": "100",
      "location": "DOWNTOWN LA STUDIO",
      "date": "AUGUST 2025"
    }
  },
  {
    "id": "photo-platini-jeans-9a41446150e6fbfa857631af-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Product / E-commerce",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Ecommerce Photography/9a41446150e6fbfa857631af_rw_1920.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/5.6",
      "shutter": "1/125s",
      "iso": "100",
      "location": "DOWNTOWN LA STUDIO",
      "date": "AUGUST 2025"
    }
  },
  {
    "id": "photo-platini-jeans-9f7d049f6b213314374ede51-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Product / E-commerce",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Ecommerce Photography/9f7d049f6b213314374ede51_rw_1920.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/5.6",
      "shutter": "1/125s",
      "iso": "100",
      "location": "DOWNTOWN LA STUDIO",
      "date": "AUGUST 2025"
    }
  },
  {
    "id": "photo-platini-jeans-b20a38200650d249fedc749b-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Product / E-commerce",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Ecommerce Photography/b20a38200650d249fedc749b_rw_1920.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/5.6",
      "shutter": "1/125s",
      "iso": "100",
      "location": "DOWNTOWN LA STUDIO",
      "date": "AUGUST 2025"
    }
  },
  {
    "id": "photo-platini-jeans-b2917169b4681344feded67d-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Product / E-commerce",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Ecommerce Photography/b2917169b4681344feded67d_rw_1920.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/5.6",
      "shutter": "1/125s",
      "iso": "100",
      "location": "DOWNTOWN LA STUDIO",
      "date": "AUGUST 2025"
    }
  },
  {
    "id": "photo-platini-jeans-da243c3af7beed92b491308c-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Product / E-commerce",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Ecommerce Photography/da243c3af7beed92b491308c_rw_1920.jpg",
    "metadata": {
      "camera": "Sony A7R V",
      "lens": "FE 24-70mm f/2.8 GM II",
      "aperture": "f/5.6",
      "shutter": "1/125s",
      "iso": "100",
      "location": "DOWNTOWN LA STUDIO",
      "date": "AUGUST 2025"
    }
  },
  {
    "id": "photo-platini-jeans-102b1298ac8c9a3bee6f7b18-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Lifestyle / Editorial",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Lifestyle Photography/102b1298ac8c9a3bee6f7b18_rw_1920.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 35mm f/1.4 ASPH",
      "aperture": "f/1.4",
      "shutter": "1/500s",
      "iso": "64",
      "location": "ARTS DISTRICT, LOS ANGELES",
      "date": "SEPTEMBER 2025"
    }
  },
  {
    "id": "photo-platini-jeans-3bdef4d5e19ecc0d7e5f74c9-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Lifestyle / Editorial",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Lifestyle Photography/3bdef4d5e19ecc0d7e5f74c9_rw_1920.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 35mm f/1.4 ASPH",
      "aperture": "f/1.4",
      "shutter": "1/500s",
      "iso": "64",
      "location": "ARTS DISTRICT, LOS ANGELES",
      "date": "SEPTEMBER 2025"
    }
  },
  {
    "id": "photo-platini-jeans-4e258022a09102117577c468-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Lifestyle / Editorial",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Lifestyle Photography/4e258022a09102117577c468_rw_1920.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 35mm f/1.4 ASPH",
      "aperture": "f/1.4",
      "shutter": "1/500s",
      "iso": "64",
      "location": "ARTS DISTRICT, LOS ANGELES",
      "date": "SEPTEMBER 2025"
    }
  },
  {
    "id": "photo-platini-jeans-518d0d2471c414178e5d65ee-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Lifestyle / Editorial",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Lifestyle Photography/518d0d2471c414178e5d65ee_rw_1920.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 35mm f/1.4 ASPH",
      "aperture": "f/1.4",
      "shutter": "1/500s",
      "iso": "64",
      "location": "ARTS DISTRICT, LOS ANGELES",
      "date": "SEPTEMBER 2025"
    }
  },
  {
    "id": "photo-platini-jeans-96e464de25a3566d9fb0d107-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Lifestyle / Editorial",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Lifestyle Photography/96e464de25a3566d9fb0d107_rw_1920.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 35mm f/1.4 ASPH",
      "aperture": "f/1.4",
      "shutter": "1/500s",
      "iso": "64",
      "location": "ARTS DISTRICT, LOS ANGELES",
      "date": "SEPTEMBER 2025"
    }
  },
  {
    "id": "photo-platini-jeans-f0fc67b4bd4ef7331f5a3473-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Lifestyle / Editorial",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Lifestyle Photography/f0fc67b4bd4ef7331f5a3473_rw_1920.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 35mm f/1.4 ASPH",
      "aperture": "f/1.4",
      "shutter": "1/500s",
      "iso": "64",
      "location": "ARTS DISTRICT, LOS ANGELES",
      "date": "SEPTEMBER 2025"
    }
  },
  {
    "id": "photo-platini-jeans-fca30fc1a2370c9e8d4e86d0-rw-1920",
    "type": "photo",
    "title": "PLATINI JEANS SHOT",
    "category": "Lifestyle / Editorial",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Lifestyle Photography/fca30fc1a2370c9e8d4e86d0_rw_1920.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 35mm f/1.4 ASPH",
      "aperture": "f/1.4",
      "shutter": "1/500s",
      "iso": "64",
      "location": "ARTS DISTRICT, LOS ANGELES",
      "date": "SEPTEMBER 2025"
    }
  },
  {
    "id": "photo-platini-jeans-kitestudios6-21107678-514410792233560-1058325519927345152-n",
    "type": "photo",
    "title": "21107678 514410792233560 1058325519927345152 N",
    "category": "Lifestyle / Editorial",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Lifestyle Photography/kitestudios6_21107678_514410792233560_1058325519927345152_n.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 35mm f/1.4 ASPH",
      "aperture": "f/1.4",
      "shutter": "1/500s",
      "iso": "64",
      "location": "ARTS DISTRICT, LOS ANGELES",
      "date": "SEPTEMBER 2025"
    }
  },
  {
    "id": "photo-platini-jeans-kitestudios6-21147688-128859881069544-6113473878103687168-n",
    "type": "photo",
    "title": "21147688 128859881069544 6113473878103687168 N",
    "category": "Lifestyle / Editorial",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Lifestyle Photography/kitestudios6_21147688_128859881069544_6113473878103687168_n.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 35mm f/1.4 ASPH",
      "aperture": "f/1.4",
      "shutter": "1/500s",
      "iso": "64",
      "location": "ARTS DISTRICT, LOS ANGELES",
      "date": "SEPTEMBER 2025"
    }
  },
  {
    "id": "photo-platini-jeans-kitestudios6-22857611-2042022399412019-909932394100817920-n",
    "type": "photo",
    "title": "22857611 2042022399412019 909932394100817920 N",
    "category": "Lifestyle / Editorial",
    "project": "Platini Jeans",
    "src": "/portfolio/Platini Jeans/Lifestyle Photography/kitestudios6_22857611_2042022399412019_909932394100817920_n.jpg",
    "metadata": {
      "camera": "Leica M11",
      "lens": "Summilux-M 35mm f/1.4 ASPH",
      "aperture": "f/1.4",
      "shutter": "1/500s",
      "iso": "64",
      "location": "ARTS DISTRICT, LOS ANGELES",
      "date": "SEPTEMBER 2025"
    }
  },
  {
    "id": "photo-products-1fb6ce96-5d1b-476b-aa32-643f8b94d95d-rw-1920",
    "type": "photo",
    "title": "PRODUCTS SHOT",
    "category": "Product / Denim",
    "project": "Products",
    "src": "/portfolio/Products/1fb6ce96-5d1b-476b-aa32-643f8b94d95d_rw_1920.jpg",
    "metadata": {
      "camera": "Hasselblad X2D 100C",
      "lens": "XCD 90mm f/2.5",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "64",
      "location": "KITE STUDIOS - SUITE 2",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-products-3bdef4d5e19ecc0d7e5f74c9-rw-1920",
    "type": "photo",
    "title": "PRODUCTS SHOT",
    "category": "Product / Denim",
    "project": "Products",
    "src": "/portfolio/Products/3bdef4d5e19ecc0d7e5f74c9_rw_1920.jpg",
    "metadata": {
      "camera": "Hasselblad X2D 100C",
      "lens": "XCD 90mm f/2.5",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "64",
      "location": "KITE STUDIOS - SUITE 2",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-products-4e258022a09102117577c468-rw-1920",
    "type": "photo",
    "title": "PRODUCTS SHOT",
    "category": "Product / Denim",
    "project": "Products",
    "src": "/portfolio/Products/4e258022a09102117577c468_rw_1920.jpg",
    "metadata": {
      "camera": "Hasselblad X2D 100C",
      "lens": "XCD 90mm f/2.5",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "64",
      "location": "KITE STUDIOS - SUITE 2",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-products-518d0d2471c414178e5d65ee-rw-1920",
    "type": "photo",
    "title": "PRODUCTS SHOT",
    "category": "Product / Denim",
    "project": "Products",
    "src": "/portfolio/Products/518d0d2471c414178e5d65ee_rw_1920.jpg",
    "metadata": {
      "camera": "Hasselblad X2D 100C",
      "lens": "XCD 90mm f/2.5",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "64",
      "location": "KITE STUDIOS - SUITE 2",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-products-950fcf2e-ae7c-40c6-afc6-2fc2e4e1797c-rw-1920",
    "type": "photo",
    "title": "PRODUCTS SHOT",
    "category": "Product / Denim",
    "project": "Products",
    "src": "/portfolio/Products/950fcf2e-ae7c-40c6-afc6-2fc2e4e1797c_rw_1920.jpg",
    "metadata": {
      "camera": "Hasselblad X2D 100C",
      "lens": "XCD 90mm f/2.5",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "64",
      "location": "KITE STUDIOS - SUITE 2",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-products-96e464de25a3566d9fb0d107-rw-1920",
    "type": "photo",
    "title": "PRODUCTS SHOT",
    "category": "Product / Denim",
    "project": "Products",
    "src": "/portfolio/Products/96e464de25a3566d9fb0d107_rw_1920.jpg",
    "metadata": {
      "camera": "Hasselblad X2D 100C",
      "lens": "XCD 90mm f/2.5",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "64",
      "location": "KITE STUDIOS - SUITE 2",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-products-f0fc67b4bd4ef7331f5a3473-rw-1920",
    "type": "photo",
    "title": "PRODUCTS SHOT",
    "category": "Product / Denim",
    "project": "Products",
    "src": "/portfolio/Products/f0fc67b4bd4ef7331f5a3473_rw_1920.jpg",
    "metadata": {
      "camera": "Hasselblad X2D 100C",
      "lens": "XCD 90mm f/2.5",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "64",
      "location": "KITE STUDIOS - SUITE 2",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-products-fca30fc1a2370c9e8d4e86d0-rw-1920",
    "type": "photo",
    "title": "PRODUCTS SHOT",
    "category": "Product / Denim",
    "project": "Products",
    "src": "/portfolio/Products/fca30fc1a2370c9e8d4e86d0_rw_1920.jpg",
    "metadata": {
      "camera": "Hasselblad X2D 100C",
      "lens": "XCD 90mm f/2.5",
      "aperture": "f/8.0",
      "shutter": "1/125s",
      "iso": "64",
      "location": "KITE STUDIOS - SUITE 2",
      "date": "OCTOBER 2025"
    }
  },
  {
    "id": "photo-quinceanera-quinceanera-cover",
    "type": "photo",
    "title": "Quinceanera Cover",
    "category": "Event / Cinematic",
    "project": "Quinceanera",
    "src": "/portfolio/Quinceanera/Quinceanera Cover.jpg",
    "metadata": {
      "camera": "Sony FX3 Cinema",
      "lens": "FE 50mm f/1.2 GM",
      "aperture": "f/1.2",
      "shutter": "1/240s",
      "iso": "320",
      "location": "THE PLAZA HOTEL, LA",
      "date": "APRIL 2025"
    }
  },
  {
    "id": "photo-quinceanera-quinceanera-146278770-110576184371294-8053248095299769303-n",
    "type": "photo",
    "title": "Quinceanera 146278770 110576184371294 8053248095299769303 N",
    "category": "Event / Cinematic",
    "project": "Quinceanera",
    "src": "/portfolio/Quinceanera/quinceanera_146278770_110576184371294_8053248095299769303_n.jpg",
    "metadata": {
      "camera": "Sony FX3 Cinema",
      "lens": "FE 50mm f/1.2 GM",
      "aperture": "f/1.2",
      "shutter": "1/240s",
      "iso": "320",
      "location": "THE PLAZA HOTEL, LA",
      "date": "APRIL 2025"
    }
  },
  {
    "id": "photo-toandme-photo-2022-06-30-07-45-52-pm",
    "type": "photo",
    "title": "Photo 2022 07 45 52 Pm",
    "category": "Editorial / Brand",
    "project": "TOANDME",
    "src": "/portfolio/TOANDME/Photo 2022-06-30 07.45.52 PM.jpg",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Summicron-SL 50mm f/2 ASPH",
      "aperture": "f/2.0",
      "shutter": "1/200s",
      "iso": "200",
      "location": "MALIBU COAST, CALIFORNIA",
      "date": "JUNE 2025"
    }
  },
  {
    "id": "photo-toandme-snapinsta-to-649244578-18094838306079035-4988156940014173278-n",
    "type": "photo",
    "title": "649244578 18094838306079035 4988156940014173278 N",
    "category": "Editorial / Brand",
    "project": "TOANDME",
    "src": "/portfolio/TOANDME/SnapInsta.to_649244578_18094838306079035_4988156940014173278_n.jpg",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Summicron-SL 50mm f/2 ASPH",
      "aperture": "f/2.0",
      "shutter": "1/200s",
      "iso": "200",
      "location": "MALIBU COAST, CALIFORNIA",
      "date": "JUNE 2025"
    }
  },
  {
    "id": "photo-toandme-snapinsta-to-651273480-18094455428047759-5856402615153129018-n--1-",
    "type": "photo",
    "title": "651273480 18094455428047759 5856402615153129018 N (1)",
    "category": "Editorial / Brand",
    "project": "TOANDME",
    "src": "/portfolio/TOANDME/SnapInsta.to_651273480_18094455428047759_5856402615153129018_n (1).jpg",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Summicron-SL 50mm f/2 ASPH",
      "aperture": "f/2.0",
      "shutter": "1/200s",
      "iso": "200",
      "location": "MALIBU COAST, CALIFORNIA",
      "date": "JUNE 2025"
    }
  },
  {
    "id": "photo-toandme-toandme-1x1-5312",
    "type": "photo",
    "title": "Toandme 1x1",
    "category": "Editorial / Brand",
    "project": "TOANDME",
    "src": "/portfolio/TOANDME/TOANDME_1x1-5312.jpg",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Summicron-SL 50mm f/2 ASPH",
      "aperture": "f/2.0",
      "shutter": "1/200s",
      "iso": "200",
      "location": "MALIBU COAST, CALIFORNIA",
      "date": "JUNE 2025"
    }
  },
  {
    "id": "photo-toandme-toandme-1x1-5330",
    "type": "photo",
    "title": "Toandme 1x1",
    "category": "Editorial / Brand",
    "project": "TOANDME",
    "src": "/portfolio/TOANDME/TOANDME_1x1-5330.jpg",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Summicron-SL 50mm f/2 ASPH",
      "aperture": "f/2.0",
      "shutter": "1/200s",
      "iso": "200",
      "location": "MALIBU COAST, CALIFORNIA",
      "date": "JUNE 2025"
    }
  },
  {
    "id": "photo-toandme-toandme-1x1-5356",
    "type": "photo",
    "title": "Toandme 1x1",
    "category": "Editorial / Brand",
    "project": "TOANDME",
    "src": "/portfolio/TOANDME/TOANDME_1x1-5356.jpg",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Summicron-SL 50mm f/2 ASPH",
      "aperture": "f/2.0",
      "shutter": "1/200s",
      "iso": "200",
      "location": "MALIBU COAST, CALIFORNIA",
      "date": "JUNE 2025"
    }
  },
  {
    "id": "photo-toandme-toandme-1x1-5358",
    "type": "photo",
    "title": "Toandme 1x1",
    "category": "Editorial / Brand",
    "project": "TOANDME",
    "src": "/portfolio/TOANDME/TOANDME_1x1-5358.jpg",
    "metadata": {
      "camera": "Leica SL2",
      "lens": "Summicron-SL 50mm f/2 ASPH",
      "aperture": "f/2.0",
      "shutter": "1/200s",
      "iso": "200",
      "location": "MALIBU COAST, CALIFORNIA",
      "date": "JUNE 2025"
    }
  }
];

export const projectsList = [
  "Ecommerce",
  "Fashion",
  "Genki Prints",
  "GLYF STUDIO",
  "Kevora",
  "Platini Jeans",
  "Products",
  "Quinceanera",
  "TDM",
  "TOANDME"
] as const;
